#!/bin/sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

#xsetroot -solid grey

#vncconfig -iconic &
#cut and paste remains flakey.. so try -nowin ??
vncconfig -nowin &

#I like one terminal with lots of tabls..
gnome-terminal --geometry=100x45 &

# and another for root..
gnome-terminal --geometry=100x45 &

#big emacs running its gnuclien server
emacs --funcall=server-start --geometry=100x49-0+0 &

#gnome window manager.. can only run one in same session, so use 2d session for vncserver
gnome-session --session=ubuntu-2d &

